[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
solana-client = "2.3.7"
solana-sdk = "2.3.1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
clap_mangen = "0.2.29"
